### ISSUE TITLE
does not look at src/ folder

### ISSUE THREAD

**Issue by rbuckland** [tiangolo/poetry-version-plugin#44]
We have the alternative standard  layout of a src folder

```
pyproject.toml
src/module_thing/__init__.py
```

this plugin is trying to read 
```
pyproject.toml
module_thing/__init__.py
```

**Comment by Messinger** [comment]
yes. Defining a prefix where to search for the package base folder would be really useful. Using "`src/<packagename>`" is some kind of standard because in larger projects you need some data beside the package itself. 

Eg, having a kind of "prefix" as configure option would be very helpul, eg.,

```
[tool.poetry-version-plugin]
source = "init"
search="backend"
```

or 

```
[tool.poetry-version-plugin]
source = "init"
search="src"
```

would improve the usability of this nice plugin a lot.

**Comment by kzych-inpost** [comment]
> I think for best compatibility, this could be inferred from the "packages" config from field, eg
> 
> `packages = [{include = "mypackage", from = "src"}]`

It still does not work this way :/

**Comment by tiangolo** [comment]
Thanks for the patience with my reply! :sweat_smile: 

I just marked this project as deprecated, I'm currently not using it and I think these ideas can be achieved in better ways: https://github.com/tiangolo/poetry-version-plugin#-warning-deprecated-

Given that I'll close this one, but thanks for the interest! :coffee:
